### ISSUE TITLE
Device resolution sometimes cropping out framerate

### ISSUE THREAD

**Issue by mrmacright** [cirquit/trdrop#102]
Some devices don't show correctly in trdrop, such as my iPhone 12 Pro. iPhone 12 Pro has a resolution of 2532‑by‑1170. 

See part of the bottom is cut off. 

![My_Time_at_Portia_-_iOS_Performance_Review 00_05_40_10 Still001](https://user-images.githubusercontent.com/83794957/128473259-480f0b93-4f5e-422c-99c3-eff80d766d7b.jpg)

![My Time at Portia - iOS Performance Review 00_05_45_04 Still003](https://user-images.githubusercontent.com/83794957/128474105-d161c5b2-7814-47db-9b4d-2f019b6fb301.jpg)

**Comment by illusion0001** [comment]
Looks like graph height is still fixed to 1440px. Plot is out of bounds. 
What resolution are you exporting at?
