### ISSUE TITLE
120 FPS lossless recording stuck at 66 FPS in Export

### ISSUE THREAD

**Issue by mrmacright** [cirquit/trdrop#103]
![Screenshot 2021-09-10 114101](https://user-images.githubusercontent.com/83794957/132785467-6bea64ae-633b-4005-a453-721657d7e492.png)

Hello. I am trying to capture 120 FPS gameplay on my M1 13" MacBook Pro. However, when I Export the video from trdrop it sticks to 66 FPS, while the SteamFPS counter in Dying Light shows over 110 FPS. Here is the [clip](https://drive.google.com/file/d/1sSgvAiDd0Sk4lFx2RUazT6n0JYLe6-0o/view?usp=sharing)

Do I need to change something in the Options menu? Or does the program not support 120 FPS yet? 

![Screenshot 2021-09-10 113616](https://user-images.githubusercontent.com/83794957/132785469-1fb55472-adf3-4b5f-b211-98f2b847a991.png)

My setup: 
- MBP is connected via [USB-C Digital AV Multiport Adapter](https://www.apple.com/au/shop/product/MUF82ZA/A/usb-c-digital-av-multiport-adapter) to [4K60 Pro MK.2](https://www.elgato.com/en/game-capture-4k60-pro) which is inside a [HighPoint Thunderbolt PCIe Expansion Chassis](https://highpoint-tech.com/USA_new/series-rs6661a-overview.htm)
- HighPoint Thunderbolt PCIe Expansion Chassis is connected to a 5K iMac which is recording the MBP via OBS under Windows 10 Boot Camp. 
- On the MBP, I have put the Refresh Rate to 120 HZ in the display settings. 

<img width="792" alt="Screen Shot 2021-09-10 at 11 46 38 am 2" src="https://user-images.githubusercontent.com/83794957/132785695-44b53795-b87c-4010-8e47-90279fd6f596.png">

**Comment by illusion0001** [comment]
Trdrop does support arbitrary framerates, double check your recording setup. 
Sample https://youtu.be/pyq2Szb3orE

**Comment by mrmacright** [comment]
Yep. I tried recording from a PS5 and it worked great. So it's just the USB-C to HDMI cable looks to only output 60HZ. I need to find one that supports 120HZ, but I don't think that is a thing yet :(
