### ISSUE TITLE
Input video with fps other than 60 is converted to 60

### ISSUE THREAD

**Issue by tamodolo** [cirquit/trdrop#11]
This causes video to speed up or slow down depending of the frame rate.

I found this while testing PS4 internal capture. Probably analising other fps than 60 don't make sense so feel free to close the ticket if this support don't have any appliance.

Really nice work btw.

**Comment by cirquit** [comment]
You're right, this should be possible. In fact is already some functionality there to enable the analysis of < 60 fps videos. We're going to try to fix this in the `v0.3` release in the next weeks.

Thank you for creating the issue and testing the software!

**Comment by tamodolo** [comment]
You're welcome! This is really a nice software so I'll keep testing and posting issues as I find them.

**Comment by cirquit** [comment]
Should work now, unfortunately I can't test this because I don't have any videos `< 60` fps. There will be a new release in the next hours.

**Comment by tamodolo** [comment]
Nice! I'll test when the binary is released and I'll let you know if it's working.

**Comment by tamodolo** [comment]
This issue is fixed. Encoder now follows the source fps. Tested with 30 and 120 fps video.
