### ISSUE TITLE
How can i change my graph view

### ISSUE THREAD

**Issue by Ashish-Raturi** [cirquit/trdrop#116]
How can i change a graph like this

![image](https://user-images.githubusercontent.com/50191855/144048170-9dd0a4d7-ac5e-4fed-b58b-d8d335230840.png)

source
https://www.youtube.com/watch?v=jM7Ed7OjSRo

**Comment by cirquit** [comment]
This is enabled via `Graph Centering`. In the new version of the software this will be documented better.
