### ISSUE TITLE
Graph line extrapolates graph top limit when fps is over 60

### ISSUE THREAD

**Issue by tamodolo** [cirquit/trdrop#12]
This probably is a known issue but I'll open a ticket for this to stay as a reminder.

I found this when testing 120 fps video. Graph line goes up so much that ended in the middle of the screen. 

Probably it is more interesting to develop a gui so no hurry to fix this.

**Comment by MujoA** [comment]
Yes, this is a known issue. So far, only videos up to 60fps are properly supported. We will fix this at a later stage but it's not a priority right now. Thanks for the reminder though :)

**Comment by tamodolo** [comment]
I really find this software awesome! I'll keep helping reporting anything I find :D

**Comment by cirquit** [comment]
This is now fixed in the GUI version, as we now support any framerate.
