### ISSUE TITLE
Unexpected results? 

### ISSUE THREAD

**Issue by cheapest-energy-windows** [cirquit/trdrop#129]
I'm trying to do a FPS analysis of The Ascent on PS4. I'm getting weird results, 40-45FPS while I was expecting 30 or less. Is this something we could expect with parts of the screen being fully blacked out? Also seeing this with other scenes were there is color/sometihng happing without the black parts on the screen. I was wondering if someone is willing to have a look at the recording/run it through Trdrop. Btw seeing the same on PS4 Pro.

https://mega.nz/file/BYI3TRjb#DnRKTr_Kbp6FyP-OnRtaXMqBtVpzc8oRNqu8TmK-xSg

**Comment by illusionyy** [comment]
Can't download on Mega, file size too big + Quota limitations

**Comment by cheapest-energy-windows** [comment]
> Can't download on Mega, file size too big + Quota limitations

Thanks for the reply, fixed the quota issue. If still unable to download I’ll upload smaller samples. 

Additional I noticed it was not really detecting some freezes, I believe you had similar issue before.

Appreciated!

**Comment by illusionyy** [comment]
Yea, upload smaller sample or another host like Google drive

**Comment by cheapest-energy-windows** [comment]
Uploading atm, this is the url to the folder: https://drive.google.com/drive/folders/15CLRPLrh_sCBhv-9g0lu_ELLBHQuX_Bw?usp=sharing

Uploading two samples, first one should be visible/complete within 15 minutes. My upload speed is limited to 50Mb/s unfortunately. In the meantime I noticed you can disable Motion Blur in this title, will see if that makes any difference at all.

Edit: upload is ready.

**Comment by cheapest-energy-windows** [comment]
Update on this from my side: 

Additional things tried:
Disable Montion Blur. Same results. 
Played with Pixel-diff (just for the heck of it). No difference until you go in very high numbers and FPS drops to nothing. 
Crop image to just process a piece of the screen. Same results.

1) Somehow it feels extremely sluggish but potential there is an unlocked FPS going on?
2) Freezes definitely not being detected or insufficient. 
3) Trying to verify with the studio on Twitter (long shot) what the target FPS should be.

Atm no other ideas.
