### ISSUE TITLE
msvcp140d.dll is missing

### ISSUE THREAD

**Issue by fpsTester** [cirquit/trdrop#14]
Hi, when i open trdrop v0.3 it says msvcp140d.dll is missing....
Do i need to install some visual c++ ? 
I tried to download msvcp140d.dll and paste it to the Windows/SysWOW64, but nothing changed 
I am using Windows 10 64bit. 
 I hope someone will help :)

**Comment by tamodolo** [comment]
This is a known issue. The program needs the debug version of those dlls to run. Just install Visual Basic SDK to solve this issue while devs don't change to runtime dlls.

**Comment by EposVox** [comment]
Has this been fixed yet? I get that warning and "ucrtbased.dll" missing and another VS runtime dll missing. I have Visual Studio installed, but I can't find any actual info on downloading Visual Studio SDK :/

**Comment by cirquit** [comment]
No, we're very unhappy with the way how VS compilation works and don't know how to get it running in any other way than with the Debug versions of the libraries. If anybody can point me into the right direction how to resolve this issue I might be able to allocate some time.

My understanding is that we would need to recompile the sources of every library we use in Release mode, which didn't work for the yaml parsing library.

This project is currently put on hold, because both me and @MujoA are very busy with work :(

**Comment by cirquit** [comment]
I think the `Windows 10 SDK ... C++` may be needed.

**Comment by jcchg** [comment]
I installed all these, but still getting the error. Sorry if I'm skipping an obvious step, I'm a newbie. Thanks for responding.

https://i.imgur.com/drezoZ1.png
https://i.imgur.com/eRMQYFg.png

**Comment by PathogenDavid** [comment]
Hey everyone! I watched @EposVox's video in which [he mentioned wanting to use this program](https://www.youtube.com/watch?v=gQru1rOSWu0&t=91). Long story short, I fixed things up and got this project building without the issues with dependencies on the debug runtime.

You can download my fork here: [v0.3-pathogen](https://github.com/PathogenDavid/trdrop/releases/tag/v0.3-pathogen)

If any of you are interested in trying to modify this thing, I've provided overly-detailed building instructions here: [BUILDING.md](https://github.com/PathogenDavid/trdrop/blob/fcb16e84297b5959db132f536c286fc3aa7783d0/BUILDING.md)

**Comment by PathogenDavid** [comment]
@cirquit If you're interested in merging my changes, I can submit a pull request. I'll warn you that I changed how the project accesses dependencies. In particular, dependencies are now managed in a property page, which are not shown in Visual Studio by default. Go to "View > Other Windows > Property Manager" to view them.

If you have any questions about why I did certain things, feel free to ask.

**Comment by cirquit** [comment]
Yes, absolutely! Please submit a pull request, we'll try to review and test it asap. Thank you for your time and effort!

**Comment by PathogenDavid** [comment]
Done, no problem! PR submitted as #20

**Comment by cirquit** [comment]
@jcchg @EposVox @fpsTester Please try the [newest release](https://github.com/cirquit/trdrop/releases/tag/v03.1) and notify us if it's working properly in this issue.
