### ISSUE TITLE
Quieter scenes not detected as changed even if pixel-diff is set to 0

### ISSUE THREAD

**Issue by tamodolo** [cirquit/trdrop#16]
I noticed that while testing battle scenes from neptunia RE;Birth 1. FPS drops in scenes while the game is waiting for player's input. There is some minor movements like range glow and a slowly spining circle on character's avatar that have the turn. The game is running at flawless 60fps clearly but trdrop can't see the changes dropping fps even with pixel-diff set to 0 (in tests I saw that the program gets more permissive to change with higher value).

Scene captured using shadowplay at 130mbits to avoid quality loss as much as possible while keeping the 60fps target.

tested using 0.3 alpha build

**Comment by MujoA** [comment]
The reason it thinks it is a frame drop even though pixels are changing might be that it is also falsely perceived as a frame tear. Frames that tear too much (above the set lineDifference limit) are not counted as new frames. Are tears displayed in the graph during that scene? Please try setting the lineDifference to 1 while keeping the pixelDifference 0 and see if that changes anything.

**Comment by tamodolo** [comment]
As video buffer capture don't have frame tears even with vsync off, this option is keeped at 100% (line-difference: 100; default is 0.6).

Changing to 1 seems to have the same effect as 100. No tears are detected.

**Comment by MujoA** [comment]
It's hard to tell without having the video to test it with. Could you somehow provide the video so I can check it out? That would be quite helpful. Just a couple of seconds where that particular scene is.

**Comment by tamodolo** [comment]
Certainly!

I don't have the original video I detected this anymore but I just captured this one:

https://www.dropbox.com/s/dofhy4xhjcbe25f/trdrop.7z?dl=0

Also in this video the drop is less intensive than the first one but it's still there. I'm sending the video, the output, the config file and the CVS.

**Comment by MujoA** [comment]
Thank you!

I will check it out later when I have some time and hopefully see what the problem is.

**Comment by OnlyJiBiR** [comment]
i think that shadowplay is causing the problem not teardrop because shadowplay some time use a "VFR" when recording.

**Comment by cirquit** [comment]
Now you can check for yourself with the difference frames option where the white pixels are located.
