### ISSUE TITLE
Tear Detection not working properly

### ISSUE THREAD

**Issue by ArctiCMooN** [cirquit/trdrop#17]
Tear detection not working properly. Test video:
Project CARS 2, grabbed from PS4, 1080p60, uncompressed video file:
https://1drv.ms/v/s!AkWwKG2Adtp_gbwqSGsNopFd9LSiug

Doesn't count any tears, although the video shows quite heavy tearing, doesn't change when pixel count is 0, 5 or 8. Tearing was set to 0.6.

**Comment by MujoA** [comment]
Thanks for uploading a video. So far, trdrop can only detect "full tears", meaning the frame is "cut" into two parts. The tearing in the video you uploaded is more in a "banding" fashion in the middle of the frame. The image below shows where the tear occurs. The black bar across the frame is what's left of the previous frame. If it was a full tear, the whole top (or bottom) of the frame would be black.

![image](https://user-images.githubusercontent.com/10074399/30602276-652a7600-9d64-11e7-9494-a21325a12ac4.png)

We might add the detection for these kind of tears in the future. Unfortunately, we haven't really had much time to further develop trdrop in the last couple of months. Hopefully that will change during the holidays. Feel free to submit any issues you find until then :)
