### ISSUE TITLE
Output BMPs of just chart?

### ISSUE THREAD

**Issue by addisokw** [cirquit/trdrop#18]
Hi!

I was wondering if it's at all possible for the bmp output option to display just the chart frames with a transparency so it can be overlayed on top of video. Our specific use case demands we overlay the chart instead of having it baked into one single video or bmp stream.

**Comment by cirquit** [comment]
Theoretically - yea. Unfortunately both me and @MujoA don't have much spare time to bring into the project right now. 

A quick fix for this would probably to create a new frame with the corrent size [here](https://github.com/cirquit/trdrop/blob/master/trdrop_c/trdrop_c/TaskScheduler.h#L185) and replace the `merged` frame with your new one. Then all the `PostTasks` would use the new frame with (e.g green background) to draw the graph, fps, etc.

You can disable certain tasks (draw FPS) [here](https://github.com/cirquit/trdrop/blob/master/trdrop_c/trdrop_c/main.cpp#L131) by commenting the line.

**Comment by EposVox** [comment]
I definitely would love this feature, too.

**Comment by cirquit** [comment]
Got an experimental version of this version working for me. Had to change the `bmp` output to `png` but I think this doesn't matter for most people?

Implemented here: a17ca43c6901a6299151278135ffee48f6233a88

Please test this feature, if it's working for you I'll to an "official" release.  Unfortunately, github doesn't allow bigger files than 10MB as attachment. Here's a [mega link](https://mega.nz/#!GxwXFLBb!WQOZjph05g4vxWi1SSviOY7lbsDKvfbeWiWpOUsxfMw) to the usual `.zip` archive. 

Example image is attached.
![trdrop-output-0000074](https://user-images.githubusercontent.com/9363632/38344058-c2401b74-3887-11e8-8464-d956d74cfa0c.png)

**Comment by EposVox** [comment]
PNG is perfect for me. Didn't think BMP supported transparency, anyway. Will test soon, hopefully it satisfies addisokw, too!

**Comment by ImplyingKinpatsu** [comment]
Did the feature not work? The MEGA file to the test version was removed

**Comment by cirquit** [comment]
Oh, that's my bad. I recently cleaned up my mega account and accidentally deleted the version. I'll try to find some time to reupload it.

**Comment by ImplyingKinpatsu** [comment]
Sounds awesome. Thanks

**Comment by cirquit** [comment]
Here's the experimental version, sorry it took so long. 

[MEGA-Link](https://mega.nz/#!rgYVQAaI!I9R61yy4OcOR6UfkcCDO_Bd0qVCk7egBV7Syer0bqfo)

**Comment by addisokw** [comment]
Sorry for just now getting back to this thread, but I tested your preview build and this new feature works great! 

I'll go ahead and close the issue.
