### ISSUE TITLE
Quick installation guide?

### ISSUE THREAD

**Issue by jcchg** [cirquit/trdrop#19]
https://i.imgur.com/eRMQYFg.png

**Comment by cirquit** [comment]
Please try the [newest release](https://github.com/cirquit/trdrop/releases/tag/v03.1)!

**Comment by MaartenJB** [comment]
Hi, it would be nice to have some form of installation guide.

I get this on windows 10:
![afbeelding](https://user-images.githubusercontent.com/16285840/42201599-ea6d79a0-7e98-11e8-85aa-91bb1a4ca96d.png)

don't know what I'm doing wrong here.

**Comment by MaartenJB** [comment]
it is the test video in your repository, I suppose that one should work right?

**Comment by cirquit** [comment]
Oh, this is a very old video which only has two colors. This was only to test basic OpenCV functionality and it might be in the wrong codec. Sorry for the confusion

**Comment by cirquit** [comment]
This is hopefully not needed anymore as we have an installer!
