### ISSUE TITLE
2 Qs: What are the spikes? & Donation

### ISSUE THREAD

**Issue by EposVox** [cirquit/trdrop#22]
![trdrop_c_2018-04-04_15-53-59](https://user-images.githubusercontent.com/18689681/38332038-faa768f6-3822-11e8-8e71-06c03f541a87.png)
What are these random spikes? Do they indicate tearing? Or just momentarily-read jumps in framerate? Didn't see this documented.

Also I'm going to be using this tool in a few videos once I've fine-tuned my workflow and etc. Where can I donate to the project?

**Comment by MujoA** [comment]
You are correct. The vertical lines indicate frame tears. We should probably make this more obvious somewhere in the description.

We haven't set up anything to accept donations so far, as we honestly didn't really expect such a positive response from people. We will make sure to let everyone know if we decide to set up a Patreon or something similar. 

Looking forward to seeing your content using trdrop :)
