### ISSUE TITLE
Error when trying to open

### ISSUE THREAD

**Issue by asanaparada** [cirquit/trdrop#28]
When I double click to execute the program, an error occurs and the program closes.
I'm using win 10 Ultimate 64x and the version of the trdrop is v3.1.
I downloaded a few minutes ago (3/6/2019).

![2vbldv](https://user-images.githubusercontent.com/10637454/53853929-3f433180-3fa6-11e9-9591-50e816fd34b2.gif)

![trdrop](https://user-images.githubusercontent.com/10637454/53854018-9c3ee780-3fa6-11e9-9e7d-c0dbc7e41e37.jpg)

**Comment by cirquit** [comment]
Hi! This looks like you're trying to open our default testing file (take a close look at the command line error "Sample 3 1080p Tearing Watch Dogs 2 PS4.avi"). As we don't have a GUI to open files directly, you have to use the `trdrop-config.yaml` file to write the path of the video you want to analyze directly under the `input-files` tag.

**Comment by asanaparada** [comment]
> Hi! This looks like you're trying to open our default testing file (take a close look at the command line error "Sample 3 1080p Tearing Watch Dogs 2 PS4.avi"). As we don't have a GUI to open files directly, you have to use the `trdrop-config.yaml` file to write the path of the video you want to analyze directly under the `input-files` tag.

My bad... Silly mistake mine. Sorry to bother. It's working good now.
