### ISSUE TITLE
OpenCV(3.4.1) Error: Assertion failed (0 < thickness && thickness <= MAX_THICKNESS) in cv::line...

### ISSUE THREAD

**Issue by ENunn** [cirquit/trdrop#30]
Trying to do an analysis on a game that runs in 4:3 and whenever I set the resolution to 1440x1080 it throws me up an error saying 
"OpenCV(3.4.1) Error: Assertion failed (0 < thickness && thickness <= MAX_THICKNESS) in cv::line, file C:\build\master_winpack-build-win64-vc15\opencv\modules\imgproc\src\drawing.cpp, line 1815".

Any way to fix this? Settings file is attached.
[trdrop-config.zip](https://github.com/cirquit/trdrop/files/3243140/trdrop-config.zip)

**Comment by MujoA** [comment]
Thanks for reporting this bug. I looked at the code and it seems like there is a problem whenever the writer width is less than 1920. I'm surprised this hasn't come up earlier.

We will fix this in a future release. A workaround would be to upscale your video. In your case you could use 1920x1440 as the output size to keep the same aspect ratio. You will lose a bit of image quality but it shouldn't be too bad. Let me know if that works. I will still leave the issue open so we don't forget about it.

**Comment by ENunn** [comment]
That fixed it! Thanks! Loss in quality ain't a problem for me :)

**Comment by cirquit** [comment]
With the new GUI release this should not happen anymore as we scale automatically and only allow 16:9 export resolutions.
