### ISSUE TITLE
How to install and use the program

### ISSUE THREAD

**Issue by samkarpenter** [cirquit/trdrop#31]
Hello all, this might be too basic for you, but I would like to ask someone to explain how to use the program? I launch the .exe file and after a brief DOS  window flash nothing happens. I've placed the video files in the program folder and launched it, but nothing happened. Thank you very much.

**Comment by ImplyingKinpatsu** [comment]
You need to open the .yaml files with the .exe (drag and drop it on top). It'll use the settings specified by the .yaml to find the specified video files in the same folder and process the videos

**Comment by samkarpenter** [comment]
Thank you very much for your prompt response. I really appreciate it! I have tried doing so but nothing happens. Do I need to place the video files in the root folder, and do I need to edit the file name in the .yaml file? 
Thank you in advance!

**Comment by ImplyingKinpatsu** [comment]
The videos need to be in the same folder as the .exe and the filename under the input-files needs to match the video file you want to process. Turns out that just running the exe without dragging/dropping will work and trdrop will automatically use tr-config.yaml. Can you get a screenshot of the command window before it goes away?
![image](https://user-images.githubusercontent.com/25698617/59570873-4b359980-9053-11e9-9246-dd33956c2685.png)

**Comment by samkarpenter** [comment]
Wonderful, you are amazing. Thank you for your quick response. I've edited the .yaml file with a Notepad, and upon dragging it on top of the .exe file it worked like a charm. Thank you very much!

**Comment by ImplyingKinpatsu** [comment]
No problem! Can't wait to see tests from you

**Comment by samkarpenter** [comment]
Thank you! I will test it out a bunch and report back! Thank you for the program. From the workflow perspective, it works absolutely effortlessly! If I may, could I inquire if there is a way to assign labels to the output, next to the FPS counter, such as the name of the game? Thank you!

**Comment by ImplyingKinpatsu** [comment]
I wasn't the one that made trdrop, but you'll have to put the game's name in in post if you don't want the game's name to share the same line with the FPS counter

**Comment by samkarpenter** [comment]
Understood. Thank you very much for your prompt replies. I will be in touch!
