### ISSUE TITLE
Releases for qt branch

### ISSUE THREAD

**Issue by LittleStinky123** [cirquit/trdrop#32]
Sorry if I overlooked a current build, but I only find builds for the old master branch on this repo.
I really tried to compile it myself with qt creator, but there are so many steps especially with the compiling of the extra modules of opencv and after adding every library manually to the qt project as it didn't want to use the system environment path variable I now get an 0xc000007b error when launching the resulting trdrop.exe
A build would be highly appreciated.

**Comment by MujoA** [comment]
Hi there. The qt branch is still work in progress so there is no official build yet. The manual compiling is mainly for developers. As soon as the software is ready, there will be a simple executable for people to use. We're not quite there yet, but should be pretty soon!
