### ISSUE TITLE
Framerate text's size scales with export resolution

### ISSUE THREAD

**Issue by ImplyingKinpatsu** [cirquit/trdrop#33]
It'll shrink whenever the export resolution is higher than 960x540 (Windows build)
![FPS Scaling](https://user-images.githubusercontent.com/25698617/62299911-ba602500-b42a-11e9-9ee3-2f77c19bd421.jpg)

**Comment by cirquit** [comment]
That's actually the desired functionality, but I understand that it's not really intuitive. You can set the Font size in the Options -> FPS -> Custom Font via the font-size in the font dialog.

There are two possibilities - either I completely ignore the font-size in the font dialog and set my own (similar scaling as the plots), or the user has to supply it by themselves as they see fit.

**Comment by cirquit** [comment]
Maybe a custom font size override which defaults to false may be the desired solution.

**Comment by cirquit** [comment]
Added a size override switch. After finishing with the cleanup + adding tooltips to every option, I'll publish the first non-beta version of trdrop in the next few days.

**Comment by cirquit** [comment]
The *stable* release is out, please see if the feature works for you as intended.

**Comment by ImplyingKinpatsu** [comment]
Works great! Thank you!
