### ISSUE TITLE
Program termination after 1.6GB RAM consumption

### ISSUE THREAD

**Issue by cirquit** [cirquit/trdrop#35]
After consuming 1.6 GB RAM, the program terminates because of a space leak. I already found the culprit (cv::Mat from opencv).

**Comment by MujoA** [comment]
And here's a screenshot of the error when it occurs:
![2019_08_01_18_22_16_trdrop](https://user-images.githubusercontent.com/10074399/62310494-f9719300-b489-11e9-963a-b2a9bdc843f3.jpg)

**Comment by cirquit** [comment]
Another user noticed the same problem at around `1.2 GB`

**Comment by micielk** [comment]
yup, same there, with 4K 60fps I can render 3-4 frames and program terminate without warning, on old Teardrop works without problem

**Comment by cirquit** [comment]
So the culprit was a connection between a C++-based QObject and a C++-based QML instatiated object. I send a QImage from the Exporter to the View and while sending this, the connection has to be made via the `Connection` QML Object. Therefore the images were allocated in JS but never deallocated.

A simple call to `gc();` could've saved me literally hours. I tested the memory usage on my Windows VM and got `~ 300MB` for processing three videos in parallel and exporting 4k images.

**Comment by illusion98** [comment]
is a new [release ](https://github.com/cirquit/trdrop/releases)incoming or are you going to iron out the other bugs first?

**Comment by cirquit** [comment]
@illusion98 just published the new release which should hopefully resolve all issues besides the UI ones.

**Comment by illusion98** [comment]
Fixed. Max ram usage was 622~MB for me.
![ ](https://cdn.discordapp.com/attachments/570608724205502464/607300166055231494/unknown.png)

**Comment by MujoA** [comment]
That is probably due to the 32bit nature of the program. There have been issues with compiling openCV with 64bit but we're working on it. Until then, this is likely going to remain an issue.

**Comment by cirquit** [comment]
So, after experiencing excruciating pain from compiling OpenCV from source in the Windows VM, I managed to compile a 64-bit version of the trdrop. 

If the testing with three `4k` videos is successful, I'll publish a new release asap.

**Comment by micielk** [comment]
Works now without problem, tried on few 4K60 video files

**Comment by cirquit** [comment]
Awesome! Closing this issue.
