### ISSUE TITLE
Certain footage displaying 60 FPS readings at all times regardless of what I do.

### ISSUE THREAD

**Issue by ChikoLad182** [cirquit/trdrop#41]
I've been testing trdrop on footage from a wide variety of games from both my PS4 Pro and Nintendo Switch. After tinkering around and learning the basics as best as I can, I was able to get accurate frame rate and frame time readings in most of my footage.

However, whenever I try footage of one game in particular (Spyro: Reignited Trilogy PS4), and do an image sequence export, the graph and FPS indicator always shows 60 FPS. The game itself has a 30 FPS cap, with notable drops in some places as well as frame pacing issues, so it should never say 60 FPS.

I've tried multiple things such as recording at 30 FPS (and trdrop picks up on that under the "Maximum Framerate" section of the add files screen) and limiting the trdrop graph to 30 FPS, but even doing both of these at once results in me getting a constant 60 FPS reading. I also thought it might have something to do with game's heavy motion blur, but there is an in-game option to turn it off and the issue still persisted when I turned off motion blur (I've also tried other games with heavy use of motion blur such as Spider-Man PS4 and Crash Team Racing: Nitro-Fueled PS4 and got accurate readings in those games, including any drops they experienced from their 30 FPS caps).

I'm going to assume that this isn't the only game that this could happen with so I'm wondering what the cause could be and if I could get around it? I would like to figure it out sooner rather than later too as I was planning on doing an analysis/comparison project on Spyro: Reignited Trilogy when the PC and Nintendo Switch versions release in September.

In terms of what I use to record, I use an AverMedia Live Gamer 4K capture card, and while I was initially trying Amarec 3.0 for recording software, I figured out how to record uncompressed video in OBS Studio and have since been using that. I have been outputting my footage at 1920x1080. All other games I have tried footage from give me accurate readings, it's just this one game that stays stuck at 60 FPS in the graph no matter what I do.

**Comment by micielk** [comment]
Problem occurs when You are using filters added to your grabber in OBS(sharpen or something), If you try watch video frame by frame you'll see strange color shifting between frames, that's why tdrop sees your video as 60fps

**Comment by ChikoLad182** [comment]
> Problem occurs when You are using filters added to your grabber in OBS(sharpen or something), If you try watch video frame by frame you'll see strange color shifting between frames, that's why tdrop sees your video as 60fps

This doesn't seem to be the issue, as other games work perfectly even with filters applied (both sharpen and colour correction for example's sake). Spyro does not work with or without them.

I also discovered another game that displays the same behaviour as Spyro, being Yooka-Laylee on PS4.

Can't really think of anything that might be common between the two games that would particularly cause this issue. Maybe the anti-aliasing they use, but that wouldn't make sense as I have tried plenty of games with heavy anti-aliasing and they work perfectly.

**Comment by illusion98** [comment]
Turning on delta processing should reveal what's going with each / current frame and adjust the pixel difference to be less "sensitive".

**Comment by ChikoLad182** [comment]
> Turning on delta processing should reveal what's going with each / current frame and adjust the pixel difference to be less "sensitive".

Seems like the pixel difference was the issue. Using delta rendering, I could see that every duplicate frame was being rendered basically as a fully black frame with barely any details, which it's likely picking up as new frames. Adjusting pixel difference from 0 to 5 seems to fix it for Spyro at least. Thanks for the help!

The only other issue I'm having, if anyone knows anything about it, is that when the frame rate in the game dips and trdrop is picking up on it, the "max framerate" on the graph decreases to whatever the framerate dips to, which leads to the graph line trying to stay straight on top even during dips, rather than dipping down along the graph and rising back up when the frame rate stabilises. It doesn't happen all of the time but it seems to just randomly happen so I can't identify the cause. The frame time graph works fine though.

**Comment by illusion98** [comment]
I think I already made a comment about it on another thread https://github.com/cirquit/trdrop/issues/40#issuecomment-520162906

**Comment by cirquit** [comment]
@illusion98 thanks for suggestion to use delta rendering, this was our proposed way to "debug" these kinds of problems.

@ChikoLad182  I'll close this issue as the "fixed ranges" feature is already proposed in the #40 issue. Please leave a vote by giving a thumbs up if you also wish for a certain feature! Thank you for using trdrop.
