### ISSUE TITLE
Request: Positioning of the framerate / frame time counter

### ISSUE THREAD

**Issue by karaokefreak** [cirquit/trdrop#48]
Hi
I think I sorted all the problems out that I had when I initially started using this app. Now it works just fine. Thumbs up and thanks for your efforts!

However, I have a layout request
1) I'd love to have a choice where to put the framerate counter (the digits) since the upper left corner is sometimes jammed with game stats and other HUD elements. having a choice between left or right corner and maybe a little margin for height adjustments (+ / - 100 Pixels?!?) would be great since changing the color doesn't always help.

2) The graph for frame time and frame rate always start their measuring at the far right end of the matrix. However, a better place to see the actual state of the scene would be in the middle with an additional vertical line in the matrix to show it. This way you can see somewhat ahead what is coming up, and by showing the end of the graph coming up, it also shows when the recorded scene will end (which is a good feature when you want to use transitions between different scenes with FPS measurement).

Is there any chance to get this in the next build or so?

**Comment by cirquit** [comment]
The positioning of the Framerate Text is currently calculated by the amount of videos which are loaded so they appear in the left upper corner. What I can think of is to allow for the following options:

* Left upper corner
* Center corner
* Right upper corner

Custom pixel-based positioning is quite cumbersome if they are not saved after closing the program so I'd try to not implement that until some caching is done.

As for the second feature I don't think I understand it correctly. What may be possible is to always skip `x` amount of frames, but showing the `time + x` framerate/-time, e.g looking in the future by `x` timesteps. What I don't understand about it how this is useful, as this may give a false impression about which scenes cause a slowdown. Please elaborate further!

**Comment by karaokefreak** [comment]
Hi
Thanks for your reply. 

About 1) 
Putting the frame counter in a different corner or top center would already help a lot. Thanks!

About 2)
Please watch a video by "the digital foundry". Their Framerate graph will start and stop in the center of the screen, which makes it easier to see the actual state of the graph and lets you see what is coming in the next seconds. It's just more pleasing to the eye and provides a better overview on past, present and future of the framerate. And on top of that, their framerate  & frame time graphs both run  _slower_ (so each frame-part of the graph is a little more narrow, which is nicer for the eye since the framerate graph doesn't run so fast at 60 FPS)

Here is a nice example on youtube
https://youtu.be/KREpHaA0Tbo?t=946

Thanks for your efforts!

**Comment by cirquit** [comment]
Ok so there are two issues then:

1. Update the Graphs more slowly - we already have the `Analysis range` Option for that. You have to extend the interval to your desired timeframe. But maybe we can do a better job with the default value

2. The centering of the current framerate in the graph. Now I think I understand what you meant. I'm actually quite surprised as I already thought about why DF had this centered vertical line in their graphs, now it makes sense.

I'm having mixed feelings about this feature - I definitely think it's not intuitive without an explanation and it slightly distorts the analysis as your usually can't see in the future.

If one knows about this, it makes the interpretation easier and allows the user to start to pay attention as to which frames cause the delay.

I'll think it may be possible to implement this by "holding off" the image stream by `x` frames and align it so value at the center of the graph shows the FPS of the currently rendered image.

What I'm missing is some visual explanation that the center of the graph shows the current value - I think that the vertical line is not enough to symbolize this. Maybe some sort of marker could do the job.

Do you have any suggestions for this or do you think this is usually not an issue with the target audience?

**Comment by karaokefreak** [comment]
Hi, thanks for your reply.
Actually, people viewing such analysis-videos are quite used to the centred graph due to Digital foundry (and others) doing it this way for years. Actually they have been doing it this way for over a decade, even beforre they added a frame time graph. Their first FPS analysis video came out in December 2008
(see here https://www.youtube.com/watch?v=C_EY5fZRFbE)

But as an extra hint, you could add an extra arrow above the vertical line. Not too big, just enough to make it clear. I attached an example picture.
![FramerateSugg](https://user-images.githubusercontent.com/56639285/68113506-39ff0380-fef4-11e9-8353-7dc94ed1854c.jpg)
Thank you for your efforts

**Comment by cirquit** [comment]
I think this is a solid visual cue. If anybody else has some ideas, feel free to post them so we can discuss them.

I don't know when I'll have time to work on the next release as I'm swamped with RL work right now, but I think this is a doable feature.

**Comment by karaokefreak** [comment]
Hi again
Is there any news on this? I'm not trying to push, i am just curious when you might be able to work on this. :)

**Comment by cirquit** [comment]
Hi,

I'm planning to find some time for development over the winter break (25.12 - 07.01)

**Comment by karaokefreak** [comment]
That sounds awesome, dude, thanks! Say, do you have a Paypal account, so I can donate a couple of beers to keep up your motivation? 
I also made you an Icon for this app, since you have no icon yet. Just use it if you like it.
![TR-Drop-Logo](https://user-images.githubusercontent.com/56639285/71319127-69fd6880-249a-11ea-9cdd-304f6eca5874.png)

**Comment by cirquit** [comment]
Just an FYI, I'm working on the features but I'm [waiting for the response](https://forum.qt.io/topic/110307/qabstractlistmodel-containing-a-qabstractlistmodel-for-combobox-qml) of some more experienced developers in the Qt Forum.

It seems like a very simple thing to have, but apparently having a dropdown list for every video in the Options pane is not easily possible.

**Comment by karaokefreak** [comment]
Hi there
Happy New Year ;) 
Are there any news by now concerning the update?

**Comment by karaokefreak** [comment]
Hi again-... well, it's been quite a while since the last update. 
As far as I understood, you had a problem with the menu system. But how about the centered Graph lines? Could you make an Update on TR drop that contains the centered Graph-Line, please?

**Comment by cirquit** [comment]
So I implemented the centering, it is now also configurable from the general settings.
![image](https://user-images.githubusercontent.com/9363632/103161219-bc284680-47de-11eb-95b9-302dcb1f5194.png)

It is kind of a pain in the ass, as I have to store the images which are processed but not visualized (until the graph reaches the center). So it uses ~ 3GB RAM with a 4k export and 180s analysis range. I also had to compile the program with 64-bit and not 32 bit as before for this to be possible, so hopefully this won't affect many users.

I did not implement the text positioning yet.

**Comment by karaokefreak** [comment]
Hey man, that is awesome. I totally appreciate your efforts! Thanks a lot! It makes it so much better now!

**Comment by cirquit** [comment]
I also implemented the fps text moving. 


https://user-images.githubusercontent.com/9363632/103180259-775ee700-4894-11eb-81af-d885ce414c05.mp4

I'll try to make a new release in the next few days.

**Comment by karaokefreak** [comment]
Awesome. Looking forward to testing it

**Comment by cirquit** [comment]
Release is done. Feel free to write here if you find any problems with the discussed functionality. Otherwise please open a new issue!

**Comment by karaokefreak** [comment]
Awesome. Will download it right away and check it soon! Thanks for your efforts

**Comment by cirquit** [comment]
Should all be solved for now.
