### ISSUE TITLE
Trdrop How to work

### ISSUE THREAD

**Issue by vale181** [cirquit/trdrop#49]
is there anyone who explains to me step by step how to make this program work on a video?
Thanks

**Comment by MujoA** [comment]
Could you be more specific on what exactly you need help with? Once you install trdrop it's pretty easy:
- Click File -> Add files
- Click on the first "+" and select your video
- Click File -> Export
- Choose a directory and click "Export" in the dialog

You should probably create a new directory for the export as trdrop will export each frame as an image that you can then import into a video editor as a sequence. For most accurate results, your input video should be uncompressed.

**Comment by vale181** [comment]
OK but it's gave me a 60fps contant line ma the game render at 30fps.
I recordered with elgato 60Fps maximum settings. 
how do i solve the problem?
Thanks

**Comment by MujoA** [comment]
You can adjust the pixel difference and activate delta processing to see what's going wrong. This has been discussed in https://github.com/cirquit/trdrop/issues/41
