### ISSUE TITLE
If export directory folder does not exist, no files are created

### ISSUE THREAD

**Issue by rorosaurus** [cirquit/trdrop#52]
The export will appear to be working (live preview, etc.) but no file writes appear in Resource Monitor, and no files (or directory) will be created.

Default: directory: C:/Users/rorosaurus/Videos/
Example fail directory: C:/Users/roros/Videos/test/

Fails with or without trailing `/`. I would expect the program to automatically create the directory (or prompt) if it doesn't exist. Or at least warn that no files will be created. For a long (failed) export, this is frustrating.

**Comment by cirquit** [comment]
Yea, that makes sense.

**Comment by cirquit** [comment]
Should be fixed in the next release
