### ISSUE TITLE
Export does not start from the start of the video

### ISSUE THREAD

**Issue by shinbojan** [cirquit/trdrop#54]
This problem happens pretty often when analyzing longer videos (50-100+ gb).
For example, if the video is 29 minutes long, it will export the images from the 4th minute. When I merge the images, I can see that the video is 26 minutes long instead of 29 minutes as expected.

It does not happen with smaller videos, it seems.

**Comment by cirquit** [comment]
Hm, interesting. I'm kind of dependent on OpenCV to iterate through the frames. I'll check it out when I find the time. Have you checked it with different kinds of videos by any chance? Could you also please share any meta-data such as the recording device and its settings for the raw video?

**Comment by cirquit** [comment]
So I checked how I export the image sequence and I didn't see anything obvious. Have you checked that you import the image sequence with the correct frametime (the same as it was recorded)?
