### ISSUE TITLE
Sorry I have a question on how to export videos

### ISSUE THREAD

**Issue by schaft0620** [cirquit/trdrop#56]
Windows 10, just started using the app

I am trying to figure out how to export videos. I can only export to images. I watch a video on YouTube and the users installers had a config file and .yaml files that I don't have. I am missing something here and I am not sure what. I downloaded ffmpeg because some of the posts mentioned that and I have no idea what to do with it.

Sorry and thanks for your help.

**Comment by ArkemiiZ** [comment]
I would also like to know how to use

**Comment by cirquit** [comment]
Install `ffmpeg` and open up PowerShell in the directory with the images that are named `exportsequence_XXX` with XXX being the numbers.

```bash
> ffmpeg -framerate 30 -i exportsequence_%10d.jpg  -c:v libx264 -pix_fmt yuv420p analysis.mp4
```
