### ISSUE TITLE
How do you actually export and use the files for a video?

### ISSUE THREAD

**Issue by Sogo64** [cirquit/trdrop#57]
I don't understand. It exports as jpg files. How do I get a video???

**Comment by cirquit** [comment]
Use install `ffmpeg` and open up PowerShell in the directory of the exported images with the name `exportsequence_XXX`. Execute the following command to create an `analysis.mp4` video.
```bash
> ffmpeg -framerate 30 -i exportsequence_%10d.jpg  -c:v libx264 -pix_fmt yuv420p analysis.mp4
```

**Comment by ArkemiiZ** [comment]
exportsequence_%: No such file or directory
