### ISSUE TITLE
New to Trdrop

### ISSUE THREAD

**Issue by kstarestrella** [cirquit/trdrop#60]
I'm new to trdrop and I've seen people do it reviews on it and tutorials on it but the only one I see it's from 2 years ago. Once I open up the final build 1.0.0 I can load the video and it can export the the images, but how do I convert from images to videos with sound. I'm sorry I'm new to this and I'm trying to learn. What am I missing. Thank you.

**Comment by philbng** [comment]
use Blinder here is a good Video how explain:
https://www.youtube.com/watch?v=Bgab9VC_laQ

**Comment by theterk** [comment]
https://stackoverflow.com/questions/31201164/ffmpeg-error-pattern-type-glob-was-selected-but-globbing-is-not-support-ed-by

**Comment by cirquit** [comment]
You can use your favorite video editing software to stitch the images back together, one example is ffmpeg. Download it and the following code in the command line in the directory with the images.

```bash
> ffmpeg -framerate 30 -i exportsequence_%10d.jpg  -c:v libx264 -pix_fmt yuv420p analysis.mp4
```
