### ISSUE TITLE
New bug: Keeps interpreting footage at 0 or 0.5fps

### ISSUE THREAD

**Issue by EposVox** [cirquit/trdrop#61]
So I'm testing 720p clips for the first time and I keep encountering a really strange bug where after a few seconds the framerate analysis drops to 0 or 0.5fps for the remainder of the clip. This is with forgiving pixel difference or strict. Not consistent when it happens either, just... nopes out.

You can see an example here [https://www.youtube.com/watch?v=hIAKgP63gMw](https://www.youtube.com/watch?v=hIAKgP63gMw)
This keeps happening, I can't get things to work properly now - I tried reinstalling.

**Comment by ImplyingKinpatsu** [comment]
It looks like there are black borders around the video frame, which it looks like trdrop counts as tearing. Does it have those borders in the original video file? You could try either removing the borders and running it again or have trdrop dismiss tearing if Apex Legends doesn't normally have tearing

**Comment by EposVox** [comment]
Disabling tearing did not help, but cropping it did. Yes, it was in the original, but I re-exported as lossless. Weird. Thanks!
