### ISSUE TITLE
no options to export to a video file

### ISSUE THREAD

**Issue by elyaspacha1** [cirquit/trdrop#65]
I don't have any options to export to a video file. I have only 2 options which is jpg and png. 
no mp4, avi, mkv, mov, or other options to export.
neither I can go above 60 fps

**Comment by cirquit** [comment]
Please import the image sequence into your favorite video editing software, I'm not planning to include this in this software. Please elaborate what you mean that can't go above 60 FPS, as there is no framerate analysis cap from what I remember.

**Comment by cirquit** [comment]
Just checked and there are no bounds for the framerate. Please upload a video if you feel this problem still persists in the new release.
