### ISSUE TITLE
Make graph centering on frame-time

### ISSUE THREAD

**Issue by temka169** [cirquit/trdrop#74]
Hi! Can you please make graph centering on frame-time like on this screenshot? Thanks!
![ппп](https://user-images.githubusercontent.com/77397314/104464317-d8d8c280-55c3-11eb-8494-6aae20e3d8d0.PNG)

**Comment by cirquit** [comment]
Yea, I was already wondering if people would like to have that feature as well :) I'll add it with the next release.

**Comment by illusion0001** [comment]
Resolved in #97
