### ISSUE TITLE
Trdrops not recognising 30FPS games, counts more

### ISSUE THREAD

**Issue by masterant86** [cirquit/trdrop#75]
Hi there,

I'm using Trdrop to analyse Xbox Series X captures. The capture is done with a capture card and OBS. OBS capture is set to lossless. Whenever I analyse the footage trdrop counts too much for the 30 FPS games. For games of which I know run (almost) locked at 60 FPS the analysis seems accurate. The FPS counts goes all the way up to 50+, even with Red Dead Redemption 2 which is locked at 30FPS.

De delta rendering and tear analysis are disabled. I noticed I get almost the same results with encoder recording (HEVC) on high bitrate (200Mbit), just wanted to try to see the difference.

Any help or tips are welcome!

Thanks.

**Comment by cirquit** [comment]
Have you resolved the issue as you closed it? I would've proposed to check out the delta rendering and play around with the pixel difference setting

**Comment by masterant86** [comment]
Hi! Appreciate your message!

No I didn’t but the reason why  I closed it is because I might have found the issue:

I’m using an Elgato 4K60 S+. This device has an hardware encoder onboard to record directly to SD and it looks like it doesn’t bypass the encoder even when connected to a pc - not sure. 

I’ve ordered a new capture device which does 1080p uncompressed to test this theory. In the meantime if you wouldn’t mind explaining how I can check out the delta rendering and change pixel difference setting I would definitely give it a go!

Again thanks!

-Antonio

**Comment by cirquit** [comment]
Basically enable `delta-rendering` in the settings now. This will enable a black/white mode which will only show **different** pixels compared to the last frame. The frames are converted to greyscale for that, so every pixel has a range of 0-255.

Now the `pixel-difference` setting basically defines what counts as a different pixel. If it's set to `10`, then a pixel with the "color" `0` and a pixel at the same position in the next frame with the "color" `10` will be counted as the same. If that happens for every pixel in the image, then the frame is counted as duplicate, which affects the framerate/frametime.

You have to decide how to set pixel-difference as some games have mechanisms to make it look like you have e.g., 60 FPS when in fact its only smudge effects applied onto every second frame, while duplicating it. In reality those games/consoles would have  30 FPS. 

But as I've seen a few discussions about how to use trdrop I feel I really need to make a tutorial.

**Comment by masterant86** [comment]
Thanks for the explanation. I will do some testing with the settings and with different capture card. Will report back when I get this working, hopefully by the end of tomorrow.

**Comment by masterant86** [comment]
Hi hereby confirm the issue was stupidity (from my side). One of the Technical Marketing Managers of Elgato confirmed on Reddit that ALL the video passes through the encoder when using the 4K60 S+. 

Also; I just tired with a different capture device (Elgato HD60S+, which doesn't have compression at all) and trdrop is working beautifully. 

Thanks!

**Comment by cirquit** [comment]
Wonderful news! I'll close it then :)
