### ISSUE TITLE
Options Issues - Frametime Not Highlighted - Options not Choosable until File Chosen- Export as Video Feature Checkup 

### ISSUE THREAD

**Issue by malanthrax** [cirquit/trdrop#81]
Morning
Excellent work and I thank you.
I have a couple oddities, or they feel like it but they may not be. 

So is the frametime option supposed to be grayed out? I have never been able to adjust it or even click on it. Before or after any video loads. 

Also the options only become available once you load a video. Like pixal diff. 

Lastly, after checking into this on various places it seems like you did find out that exporting to video is fine if you don't sell the software(saw another post by you here) and various other software that does work even beyond this also doesn't have any issues doing video. So I am hoping that might be engaged at some point?

**Comment by cirquit** [comment]
Yes to frametime, it was a mock thing that didn't get implemented. And yes, the other options are only made availabe once the videos are loaded.

Yes, the video export is a future feature for now.
