### ISSUE TITLE
Program reporting FPS as lower than it actually is.

### ISSUE THREAD

**Issue by LiquifiedPizzas** [cirquit/trdrop#82]
I was trying to run a lossless video of a recently leaked N64 game (224p in a 480p recording) through the program when i noticed it was acting rather strangely. Despite the game certainly updating, and me having the pixel difference on 0, the framerate is being reported as far lower than it actually is, and it goes for long stretches of thinking there are no new frames, despite there most certainly being new frames. (Additionally, the original video was 4:3, but i had to add borders to make trdrop format on it correctly, but that's a request for another post.) Here's the video file:
https://drive.google.com/file/d/1MtiEv7bAk4nU59SIbUd6F4ZHi3udURYc/view?usp=sharing

I've tried encoding it into a few other lossless formats, in various color spaces, and nothing changes. I'm really confused as to what the issue could be, frankly. I also tried going back to 1.0.0 and got the exact same issue.

![image](https://user-images.githubusercontent.com/18299917/108614000-4eeaf900-73bc-11eb-85c7-a4a0a1abaa1a.png)
despite many frames being rendered in this timeframe, the frametime graph just stops existing, and the average is reported as hilariously low. The game's average is still hilariously low, but not THIS low.

**Comment by ImplyingKinpatsu** [comment]
This looks similar to issue #61. The white line at the bottom of the program is representing that the program is interpreting the bottom of the frame as screen tearing. Have you tried either both setting the dismissed tear percentage to 100% and disabling screen tearing analysis (assuming Dinosaur Planet does not have screen tearing) or cropping the video in something like VirtualDub using the nulltransform filter to remove the border?

**Comment by LiquifiedPizzas** [comment]
I did actually try cropping out the black border and got the same issue somehow, but now I feel silly as turning dismissed tear percentage to 100 did fix it. I could swear I turned off enable tear detection and this still happened, but turning that to 100 did fix it, so thank you.
