### ISSUE TITLE
Loseless vs uncompressed

### ISSUE THREAD

**Issue by fsimao90** [cirquit/trdrop#83]
Hi there, I've been wondering if we could get a good analysis with loseless videos. 
I've been trying with uncompressed on my Elgato 4K60 Pro using Virtualdub but my recordings are very strange, for example, if I record 1 minute of video, it will have 40 seconds running fine and the last 20 seconds will be compressed into very fast 2 seconds. 

So I was wondering if there is an alternative to capture uncompressed without sync issues or if Loseless will work fine since most programs like OBS support loseless but I don't think they support uncompressed.

Thanks for the great work so far

**Comment by cirquit** [comment]
So I really do not have any knowledge about how to record lossless videos, I'm actually only developing trdrop, not using it for myself. Please ask in the relevant forums or discord servers, I'm sure you are not the only one struggling to get this working!

**Comment by FireCulex** [comment]
UTVideo failed to capture a 20 fps stutter. There should be a warning when opening a lossless/compression to proceed at own risk and results are probably inaccurate until at which time results are independently verified.
