### ISSUE TITLE
PS5

### ISSUE THREAD

**Issue by hYPERzs** [cirquit/trdrop#84]
Hi, There is such a problem, sometimes on some games, everything is fine. It's about the PS5 + Atomos Ninja V PreRes. I tried countless options, varying HDMI versions, and settings(1.4, 2.0, Compabilyti mode). Everything is fine with the PC and XBOX Series X [https://youtu.be/Z0xZooXbs8k](url) This is not the case with all PS5 games, and I don't understand why this is the case. Here 100% is 30 fps, but Trdrop can't calculate frames [https://youtu.be/OO54OU0wnkg](url) I manually calculate how many frames In a second, i.s. 30 frames per second. If you have any thoughts, help me solve them. Thanks!

**Comment by hYPERzs** [comment]
Everything is already working

**Comment by cirquit** [comment]
Closing as this seems solved already?
