### ISSUE TITLE
Feature request Graphs without horizontal lines

### ISSUE THREAD

**Issue by masterant86** [cirquit/trdrop#92]
Hi,

Hope you're doing well. 

I have a feature request and I hope it isn't much hassle to implement, I know you mentioned you have limited time to work on the tool. It would be extremely helpful.

Is there a possibility to export the graphs without the horizontal lines background? So only the line of FPS and Frame Time itself? Everything else can stay the same. The ask is because by allowing this you can create a different format/look for it without using the csv file which would require for example AE (and scripting). The idea is to create a different layout with (in my case) Apple Motion. I can plot the lines over this new layout and be done extremely fast.

If there are like reference files for the graphs I could edit myself to remove the lines, any pointers would be sufficient and very welcome.

Thanks.

Best regards.

**Comment by cirquit** [comment]
Hi, thank you for using trdrop and caring enough to make an issue! 

So I'm not fully following unfortunately what you plan to do, but I could make an option to remove the lines. 
Could you provide me with some visual examples as to why you need this?

**Comment by masterant86** [comment]
Hi Thank you for the reply. I actually got around this issue without any adjustments needed from the original graphs. I eventually got around it with Colorize to effects and it is working fine. Did you re-open this issue? I did close it to not have you unnecessary questions build up. Again thank you and keep up the great work.

**Comment by cirquit** [comment]
Oh, it apparently wasn't closed, otherwise it would show in the timeline here. Good that fixed it yourself! Closing.
