### ISSUE TITLE
How do I capture iPhone & iPads? 

### ISSUE THREAD

**Issue by mrmacright** [cirquit/trdrop#94]
I have tried recording gameplay with both the Elgato HD60S+ and 4K60S+ with OBS Studio and then imported the video file into TRdrop... but the frame rate is incorrect. For example in GRID Autosport, the developer told me the game is locked at 60 FPS, however, TRdrop says it never gets over 13 FPS. 

I am recording with a lossless format, and it works fine with Apple TV. Does TRdrop not support aspect ratios like 4:3? 

![IMG_7617](https://user-images.githubusercontent.com/83794957/117382153-2e453080-af21-11eb-9388-b2b091091fb5.jpg)

**Comment by mrmacright** [comment]
> I have recorded gameplay with Elgato HD60S+ & 4K60S+ and OBS and then imported it into TRdrop, but the frame rate is incorrect. For example in GRID Autosport (attached), the developer told me the game is locked at 60 FPS, however, TRdrop says it never gets over 13 FPS.
> 
> ![IMG_7617](https://user-images.githubusercontent.com/83794957/117382153-2e453080-af21-11eb-9388-b2b091091fb5.jpg)

**Comment by mrmacright** [comment]
Okay I fixed the problem! Here is the solution if anyone else wants to record a mobile device. 

Stop 01: 
You have to find out the native resolution of your device. For example I am using a 12.9" iPad Pro: 
Native resolution is - 2388-by-1668. 

Step 02:
In OBS go to "Preferences", "Video" and make the "Base (Canvas Resolution) and Output (Scaled) Resolution the same as your devices native resolution. ie for me 2388-by-1668. 

Make sure "Common FPS Value" matches your device and capture card. While my iPad Pro can play games up to 120 FPS, my Elgato 4K60s+ can only record up to 60 FPS. So I limited the value to 60. 

Step 03:
Now go out "Output" in Settings. Change the "Recording Quality" and "Recording" to "Lossless Quality, Tremendously Large File Size". This will provide you with uncompressed footage that will work in Trdrop. 

Step 04: 
In TRdrop make sure "pixel difference" is set to "60" under Options.

**Comment by cirquit** [comment]
Wonderful that you made that happen! So the issue was probably that you didn't have a lossless recording going on (had that happen with OBS myself as well).

I'll keep your issue in mind as I plan to do a wiki for common problems.
