### ISSUE TITLE
Cannot choose more than 180 frames analysis range

### ISSUE THREAD

**Issue by aj752** [cirquit/trdrop#96]
Hi, 

Hopefully I'm not just doing something wrong, I read that some issues were fixed to allow an higher value than 180 frames for the range of frames per seconds and frame time. I'm using v1.1.1 but whenever I input a higher number it automatically jumps back to 180. Is there a way to increase beyond 180 or is it a feature which will be added in the future?

Thanks in advance.

**Comment by cirquit** [comment]
There's a limit set to the framerate analysis time from 30 to 180FPS (https://github.com/cirquit/trdrop/blob/master/trdrop/qml/OptionsWindow.qml#L153). What you're referring to is the maximum framerate setting where it won't scale the plot if we drop below a certain FPS.

I kind of remember trying to increase the number of processed frames and it started a little bit of lagging for me. I have to double-check that again as I'm not 100% sure if this was when I tested that, but in reality, it shouldn't be much of an issue.

The modules touched by that change are, as you said yourself, the framerate and the frame time calculation. For those, I keep a queue with that exact length (180) and just add new items to the front, and remove the old information from the back so we keep a nice container with the most up-to-date data. It shouldn't have much of an effect on performance or memory.

I'll try to see what I can do. What kind of values were you looking for? I thought 3 minutes should be typically enough of a resolution.

**Comment by masterant86** [comment]
Thank you for the reply. So 180 frames equals 3 seconds with a 60FPS video, this is for me personally fine - although I would love to see higher. With 120FPS videos is halfs down to 1,5 seconds and it is really short, you feel like it is flying by. I would personally suggest a value of max like 720. Up to 12 seconds with 60FPS or 6 seconds with 120FPS videos.

**Comment by illusion0001** [comment]
@masterant86 Please test build in #97

**Comment by masterant86** [comment]
Is this really happening 😃 

unable to test right away but will do within the next 48 hours, very excited to try it out!

**Comment by masterant86** [comment]
> @masterant86 Please test build in #97

I appologize, I wasn't able to react/test earlier like mentioned. I'm about to test right now with a few just recorded 120FPS clips. Is there something I need to be looking for or just use it like I normally would but than increase the range?

**Comment by masterant86** [comment]
> @masterant86 Please test build in #97

I tested un multiple videos, everything seems to be working perfect. All the defaults are the ones I choose so this will be my build going forward! Because the graphs are the same size, it also doesn't affect my Effects to transform the graphs to something else - which I was a bit worried about. Amazing work!

**Comment by illusion0001** [comment]
Thanks for testing :)
